//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenador
    {
        public string Identificador_E { get; set; }
        public string Nombre_E { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public int Núm_Teléfono { get; set; }
        public string Provincia { get; set; }
        public string Cantón { get; set; }
        public string Distrito { get; set; }
        public string Otras_señas { get; set; }
        public string Correo_Electrónico { get; set; }
        public string Ubicación { get; set; }
        public string Sitio_Web { get; set; }
        public string Nombre_Usuario { get; set; }
    
        public virtual Bitácora Bitácora { get; set; }
        public virtual Entrenador_Pokemon Entrenador_Pokemon { get; set; }
        public virtual Entrenador_Pokemon_Movimiento Entrenador_Pokemon_Movimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Redes_Sociales_E Redes_Sociales_E { get; set; }
    }
}
