//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1Entities3 : DbContext
    {
        public test1Entities3()
            : base("name=test1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitácora> Bitácora { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Entrenador> Entrenadors { get; set; }
        public virtual DbSet<Entrenador_Pokemon> Entrenador_Pokemon { get; set; }
        public virtual DbSet<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        public virtual DbSet<Movimiento> Movimientoes { get; set; }
        public virtual DbSet<Pokemon> Pokemons { get; set; }
        public virtual DbSet<Redes_Sociales_E> Redes_Sociales_E { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
