//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.Entrenador_Pokemon = new HashSet<Entrenador_Pokemon>();
            this.Entrenador_Pokemon_Movimiento = new HashSet<Entrenador_Pokemon_Movimiento>();
            this.Movimientoes = new HashSet<Movimiento>();
        }
    
        public int Identificador_P { get; set; }
        public string Nombre_P { get; set; }
        public string Tipo1 { get; set; }
        public string Tipo2 { get; set; }
        public int Total { get; set; }
        public int Salud { get; set; }
        public int Ataque { get; set; }
        public int Defensa { get; set; }
        public int Ataque_Especial { get; set; }
        public int Defensa_Especial { get; set; }
        public int Velocidad { get; set; }
        public int Generación { get; set; }
        public string Legendario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrenador_Pokemon> Entrenador_Pokemon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimientoes { get; set; }
    }
}
